//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from e:\tmp\parameters by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="parametersParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public interface IparametersListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="parametersParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameters([NotNull] parametersParser.ParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="parametersParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameters([NotNull] parametersParser.ParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="parametersParser.arrayArgumentsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayArgumentsList([NotNull] parametersParser.ArrayArgumentsListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="parametersParser.arrayArgumentsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayArgumentsList([NotNull] parametersParser.ArrayArgumentsListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="parametersParser.argumentsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentsList([NotNull] parametersParser.ArgumentsListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="parametersParser.argumentsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentsList([NotNull] parametersParser.ArgumentsListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="parametersParser.pterminal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPterminal([NotNull] parametersParser.PterminalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="parametersParser.pterminal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPterminal([NotNull] parametersParser.PterminalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="parametersParser.bterminal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBterminal([NotNull] parametersParser.BterminalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="parametersParser.bterminal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBterminal([NotNull] parametersParser.BterminalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="parametersParser.singleArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingleArgument([NotNull] parametersParser.SingleArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="parametersParser.singleArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingleArgument([NotNull] parametersParser.SingleArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>arrayOfValues</c>
	/// labeled alternative in <see cref="parametersParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayOfValues([NotNull] parametersParser.ArrayOfValuesContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>arrayOfValues</c>
	/// labeled alternative in <see cref="parametersParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayOfValues([NotNull] parametersParser.ArrayOfValuesContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>emptyArray</c>
	/// labeled alternative in <see cref="parametersParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmptyArray([NotNull] parametersParser.EmptyArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>emptyArray</c>
	/// labeled alternative in <see cref="parametersParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmptyArray([NotNull] parametersParser.EmptyArrayContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Number</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] parametersParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Number</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] parametersParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Integer</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInteger([NotNull] parametersParser.IntegerContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Integer</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInteger([NotNull] parametersParser.IntegerContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>String</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] parametersParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>String</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] parametersParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ObjectRef</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectRef([NotNull] parametersParser.ObjectRefContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ObjectRef</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectRef([NotNull] parametersParser.ObjectRefContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UndelimitedText</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUndelimitedText([NotNull] parametersParser.UndelimitedTextContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UndelimitedText</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUndelimitedText([NotNull] parametersParser.UndelimitedTextContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>arrayObject</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayObject([NotNull] parametersParser.ArrayObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>arrayObject</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayObject([NotNull] parametersParser.ArrayObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>True</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrue([NotNull] parametersParser.TrueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>True</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrue([NotNull] parametersParser.TrueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>False</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFalse([NotNull] parametersParser.FalseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>False</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFalse([NotNull] parametersParser.FalseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Null</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNull([NotNull] parametersParser.NullContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Null</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNull([NotNull] parametersParser.NullContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Empty</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmpty([NotNull] parametersParser.EmptyContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Empty</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmpty([NotNull] parametersParser.EmptyContext context);
}
