//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from e:\tmp\parameters.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IparametersListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public partial class parametersBaseListener : IparametersListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="parametersParser.parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameters([NotNull] parametersParser.ParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="parametersParser.parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameters([NotNull] parametersParser.ParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="parametersParser.arrayArgumentsList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayArgumentsList([NotNull] parametersParser.ArrayArgumentsListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="parametersParser.arrayArgumentsList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayArgumentsList([NotNull] parametersParser.ArrayArgumentsListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="parametersParser.argumentsList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentsList([NotNull] parametersParser.ArgumentsListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="parametersParser.argumentsList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentsList([NotNull] parametersParser.ArgumentsListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="parametersParser.pterminal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPterminal([NotNull] parametersParser.PterminalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="parametersParser.pterminal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPterminal([NotNull] parametersParser.PterminalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="parametersParser.bterminal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBterminal([NotNull] parametersParser.BterminalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="parametersParser.bterminal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBterminal([NotNull] parametersParser.BterminalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="parametersParser.singleArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingleArgument([NotNull] parametersParser.SingleArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="parametersParser.singleArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingleArgument([NotNull] parametersParser.SingleArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>arrayOfValues</c>
	/// labeled alternative in <see cref="parametersParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayOfValues([NotNull] parametersParser.ArrayOfValuesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>arrayOfValues</c>
	/// labeled alternative in <see cref="parametersParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayOfValues([NotNull] parametersParser.ArrayOfValuesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>emptyArray</c>
	/// labeled alternative in <see cref="parametersParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmptyArray([NotNull] parametersParser.EmptyArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>emptyArray</c>
	/// labeled alternative in <see cref="parametersParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmptyArray([NotNull] parametersParser.EmptyArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Number</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] parametersParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Number</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] parametersParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Integer</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInteger([NotNull] parametersParser.IntegerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Integer</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInteger([NotNull] parametersParser.IntegerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>String</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] parametersParser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>String</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] parametersParser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ObjectRef</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectRef([NotNull] parametersParser.ObjectRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ObjectRef</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectRef([NotNull] parametersParser.ObjectRefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>UndelimitedText</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUndelimitedText([NotNull] parametersParser.UndelimitedTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UndelimitedText</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUndelimitedText([NotNull] parametersParser.UndelimitedTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>arrayObject</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayObject([NotNull] parametersParser.ArrayObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>arrayObject</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayObject([NotNull] parametersParser.ArrayObjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>True</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrue([NotNull] parametersParser.TrueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>True</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrue([NotNull] parametersParser.TrueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>False</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFalse([NotNull] parametersParser.FalseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>False</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFalse([NotNull] parametersParser.FalseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Null</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNull([NotNull] parametersParser.NullContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Null</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNull([NotNull] parametersParser.NullContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Empty</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmpty([NotNull] parametersParser.EmptyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Empty</c>
	/// labeled alternative in <see cref="parametersParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmpty([NotNull] parametersParser.EmptyContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
